### PR TITLE
add: scrolling background

### PR DESCRIPTION
**Pull request by q-uint**
For further improvements the size of the vehicle is needed. This is not yet provided. ˜ 第五

### CODE REVIEW

**Review by winnie334 — CHANGES_REQUESTED** [review]
Interesting idea but the execution is kinda poor - even when the car is not expanded, you can still clearly see the position change when going out of screen. I suggest making more than one car which mimics the movement of the main car which drives in the screen as the main car drives out.

**Comment by q-uint** [comment]
I'll refactor everything first then... ♻️ 
Update coming soon.

**Comment by q-uint** [comment]
Solved 🏁.

**Comment by winnie334** [comment]
I don't even need to test out this code to see that it's great, merged!

**Pull request merged**
